# server
FROM golang:1.19 AS build

WORKDIR /app
ADD server .

RUN go build -o room .


FROM ubuntu:latest

# 证书
RUN apt-get -qq update \
    && apt-get -qq install -y --no-install-recommends ca-certificates curl

WORKDIR /app

COPY --from=build /app/room .
COPY --from=build /app/configs/openai_config.ini configs/openai_config.ini

EXPOSE 8322

CMD ["./room"]
